server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  application:
    name: CMS-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: 'lb://USER-SERVICE'
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: COURSE-SERVICE
          uri: 'lb://COURSE-SERVICE'
          predicates:
            - Path=/courses/**
          filters:
            - AuthenticationFilter
        - id: ENROLLMENT-SERVICE
          uri: 'lb://ENROLLMENT-SERVICE'
          predicates:
            - Path=/enrollments/**
          filters:
            - AuthenticationFilter
        - id: ASSIGNMENT-SERVICE
          uri: 'lb://ASSIGNMENT-SERVICE'
          predicates:
            - Path=/assignments/**
          filters:
            - AuthenticationFilter
  # security:
  #   oAuth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://auth-service:8080/auth/realms/myrealm
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'