server:
    port: 8080

Spring:
    application:
        name: cms-api-gateway

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

spring:
    cloud:
        gateway:
            routes:
            -   id: userservice
                uri: lb://USERSERVICE
                predicates:
                -   path=/users/**
            -   id: courseservice
                uri: lb://COURSESERVICE
                predicates:
                -   path=/courses/**
            -   id: enrollment-service
                uri: lb://ENROLLMENT-SERVICE
                predicates:
                -   path=/users/**
            -   id: assignment-service
                uri: lb://ASSIGNMENT-SERVICE
                predicates:
                -   path=/courses/**
