server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: 'lb://userservice'
          predicates:
            - Path=/users/**
        - id: courseservice
          uri: 'lb://courseservice'
          predicates:
            - Path=/courses/**
        - id: enrollmentservice
          uri: 'lb://enrollment-service'
          predicates:
            - Path=/enrollments/**
        - id: assignmentservice
          uri: 'lb://assignment-service'
          predicates:
            - Path=/assignments/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
